"""add_job_fields_for_apify_integration

Revision ID: 01aa6f8ffb0e
Revises: 6a8c9d2e3f4b
Create Date: 2025-10-16 11:45:07.461494

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '01aa6f8ffb0e'
down_revision = '6a8c9d2e3f4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_postings', sa.Column('linkedin_job_id', sa.String(), nullable=True))
    op.add_column('job_postings', sa.Column('employment_type', sa.String(), nullable=True))
    op.add_column('job_postings', sa.Column('seniority_level', sa.String(), nullable=True))
    op.add_column('job_postings', sa.Column('is_remote', sa.Boolean(), nullable=True))
    op.add_column('job_postings', sa.Column('industries', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('job_postings', sa.Column('salary_min', sa.Float(), nullable=True))
    op.add_column('job_postings', sa.Column('salary_max', sa.Float(), nullable=True))
    op.add_column('job_postings', sa.Column('salary_currency', sa.String(), nullable=True))
    op.add_column('job_postings', sa.Column('application_url', sa.Text(), nullable=True))
    op.add_column('job_postings', sa.Column('apify_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('job_postings', sa.Column('last_scraped_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_postings', 'last_scraped_at')
    op.drop_column('job_postings', 'apify_data')
    op.drop_column('job_postings', 'application_url')
    op.drop_column('job_postings', 'salary_currency')
    op.drop_column('job_postings', 'salary_max')
    op.drop_column('job_postings', 'salary_min')
    op.drop_column('job_postings', 'industries')
    op.drop_column('job_postings', 'is_remote')
    op.drop_column('job_postings', 'seniority_level')
    op.drop_column('job_postings', 'employment_type')
    op.drop_column('job_postings', 'linkedin_job_id')
    # ### end Alembic commands ###
