"""add_linkedin_scraper_credentials

Revision ID: d51fbc44e693
Revises: c155dfadfd92
Create Date: 2025-10-28 14:36:12.461137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd51fbc44e693'
down_revision = 'c155dfadfd92'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('linkedin_scraper_email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('linkedin_scraper_password', sa.String(), nullable=True))
    op.add_column('users', sa.Column('linkedin_credentials_consent', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'linkedin_credentials_consent')
    op.drop_column('users', 'linkedin_scraper_password')
    op.drop_column('users', 'linkedin_scraper_email')
    # ### end Alembic commands ###
