"""add_scraped_jobs_table

Revision ID: c04023fc6044
Revises: d51fbc44e693
Create Date: 2025-10-28 14:42:16.111055

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c04023fc6044'
down_revision = 'd51fbc44e693'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraped_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_resume_id', sa.UUID(), nullable=True),
    sa.Column('linkedin_post_url', sa.Text(), nullable=False),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('posted_date', sa.String(), nullable=True),
    sa.Column('is_remote', sa.Boolean(), nullable=True),
    sa.Column('employment_type', sa.String(), nullable=True),
    sa.Column('seniority_level', sa.String(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('match_reasoning', sa.Text(), nullable=True),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_resume_id'], ['uploaded_resumes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('linkedin_post_url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scraped_jobs')
    # ### end Alembic commands ###
