"""add_profile_url_field

Revision ID: b9b1f396c058
Revises: 01aa6f8ffb0e
Create Date: 2025-10-16 11:56:37.099912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9b1f396c058'
down_revision = '01aa6f8ffb0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
