"""add_cookie_persistence_to_service_accounts

Revision ID: 194ca9a4d42f
Revises: add_match_details_v2
Create Date: 2025-11-18 10:29:31.252186

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '194ca9a4d42f'
down_revision = 'add_match_details_v2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linkedin_service_accounts', sa.Column('cookies', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('linkedin_service_accounts', sa.Column('cookies_updated_at', sa.DateTime(), nullable=True))
    op.add_column('linkedin_service_accounts', sa.Column('cookies_expiry', sa.DateTime(), nullable=True))
    op.alter_column('linkedin_service_accounts', 'email',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Encrypted email',
               existing_nullable=False)
    op.alter_column('linkedin_service_accounts', 'password',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Encrypted password',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('linkedin_service_accounts', 'password',
               existing_type=sa.VARCHAR(),
               comment='Encrypted password',
               existing_nullable=False)
    op.alter_column('linkedin_service_accounts', 'email',
               existing_type=sa.VARCHAR(),
               comment='Encrypted email',
               existing_nullable=False)
    op.drop_column('linkedin_service_accounts', 'cookies_expiry')
    op.drop_column('linkedin_service_accounts', 'cookies_updated_at')
    op.drop_column('linkedin_service_accounts', 'cookies')
    # ### end Alembic commands ###
